
---
#
# WebApp Microservice Deployment + Service
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ecommerce-webapp-ingress
  labels:
    app: webapp
    tier: frontend
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  generation: 1
spec:
  rules:
  - host: ecommerce-$$DEPLOY_SUFFIX.$$DNS_SUFFIX
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: webapp
  labels:
    app: webapp
    tier: frontend
spec:
  selector:
    app: webapp
    tier: frontend
  ports:
  - name: webapp
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: sales-api
    tier: backend
spec:
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: $$REGISTRY_SERVERwebapp:$$IMAGE_VERSION
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "$$ENVIRONMENT_NAME"
        - name: ASPNETCORE_ORCHESTRATOR
          value: "k8s"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---